// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9pVyiYSTl4549sQ8PowxJxmnMugJX07U',
    appId: '1:323667673843:android:9561c22f9f861108c06d86',
    messagingSenderId: '323667673843',
    projectId: 'tinytrail-f994f',
    storageBucket: 'tinytrail-f994f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ETxIP0wmRlovCj7IGgSC6D9YLPFuJrc',
    appId: '1:323667673843:ios:da03c22537a906c1c06d86',
    messagingSenderId: '323667673843',
    projectId: 'tinytrail-f994f',
    storageBucket: 'tinytrail-f994f.firebasestorage.app',
    iosBundleId: 'com.example.tinytrail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfz68sA0xZf_47U00Lmo9lPYhx1BXn2_Q',
    appId: '1:323667673843:web:6a14c42966305b8dc06d86',
    messagingSenderId: '323667673843',
    projectId: 'tinytrail-f994f',
    authDomain: 'tinytrail-f994f.firebaseapp.com',
    storageBucket: 'tinytrail-f994f.firebasestorage.app',
    measurementId: 'G-7NCRQS9N08',
  );
}
